### ISSUE TITLE
FNF is left unplayable now

### ISSUE THREAD

**Issue by Ralsei327** [AppleHair/FNF-UnrestDiffs#5]
![image_2024-06-30_180749088](https://github.com/AppleHair/FNF-UnrestDiffs/assets/174280327/5f0a07fb-53eb-4870-884a-36ff55efec61)
Everytime I try to play the new FNF the game just has this error pop up and I can't play any of the songs. It only started happening after I downloaded new unrestricted difficulties so maybe it has smth to do with it. It also has something to do with the instrumental too, because another error revolving around such also pops up whenever picking something from story mode. I am on the v4.0 version, but I tried with the newest and i got the same issue. Please help

**Comment by AppleHair** [comment]
The instrumental thing will probably only be a problem in 0.4.0, but when it comes to the first error, I have no idea where this is coming from and it doesn't look related to anything UD does.

You should try to run FNF with UD without other mods, and maybe even re-installing FNF in a seperate folder and trying to run FNF with that. When I say FNF I mean 0.4.1 because UD is made for 0.4.1 only.

**Comment by AppleHair** [comment]
I looked at the error a bit more and I see it's running into a problem when compiling a shader which haxeflixel uses to render textures. I believe your build of FNF is broken, because there's no way any mod will prevent a shader which is used by haxeflixel from being compiled.

**Comment by Ralsei327** [comment]
Dw Thanks, I figured it out

It was actually just a unrelated cyber sensation hud mod that fucked up the shaders
